{% set name = "pixi-kernel" %}
{% set version = "0.6.6" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pixi_kernel-{{ version }}.tar.gz
  sha256: 3f437a202f8ad96893e9e5429e7235b24c463759fc6a7f84923b1bbf06699e9c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
    - nodejs
    - pip
  run:
    - python >={{ python_min }}
    - ipykernel >=6
    - jupyter_client >=7
    - jupyter_server >=2.4
    - msgspec >=0.18
    - returns >=0.23
    - tomli >=2

test:
  imports:
    - pixi_kernel
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/renan-r-santos/pixi-kernel
  summary: Jupyter kernels using Pixi for reproducible notebooks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - renan-r-santos
